### ISSUE TITLE
Reset Button does not reset everything

### ISSUE THREAD

**Issue by cayrusa** [zekash-dev/ti-sa-combat-calc#2]
It does not reset the High Alert token and the Leaders.
![image](https://user-images.githubusercontent.com/60691596/157329370-52a8113f-931e-4274-b58b-a808ae9a85e6.png)

![image](https://user-images.githubusercontent.com/60691596/157329413-01ae6d13-9455-4375-b4da-89fe949a5522.png)

**Comment by zekash-dev** [comment]
Good catch, fixed. I guess it's time to deploy a new version with some minor fixes I've made in the last month or so.
